### ISSUE TITLE
OSX build on CircleCI failing

### ISSUE THREAD

**Issue by chambbj** [conda-forge/pcl-feedstock#2]
Upon merge of #1, the OSX build on CircleCI now ends in

```
Traceback (most recent call last):
  File "/Users/distiller/miniconda3/bin/upload_or_check_non_existence", line 131, in <module>
    main()
  File "/Users/distiller/miniconda3/bin/upload_or_check_non_existence", line 121, in main
    upload(cli, fname, owner, channel)
  File "/Users/distiller/miniconda3/bin/upload_or_check_non_existence", line 68, in upload
    env=os.environ)
  File "/Users/distiller/miniconda3/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['anaconda', '--quiet', '-t', '/var/folders/ms/xg67k5sn16xc7sdr_w3q45840000gn/T/tmp610nchy8/binstar.token', 'upload', '/Users/distiller/miniconda3/conda-bld/osx-64/pcl-1.8.1-h386bb81_1.tar.bz2', '--user=conda-forge', '--channel=main']' returned non-zero exit status 1.
Exited with code 1
```

Not sure I follow. I do see a similar issue raised at https://github.com/conda-forge/conda-forge-ci-setup-feedstock/issues/12, but the build number was bumped and recipe rerendered in the PR, so it seems that couldn't be the issue.

Could use some help from @conda-forge/core. Thanks!

**Comment by isuruf** [comment]
Restarted the build and it passed. Might have been a anaconda.org server issue
